### ISSUE TITLE
Direktchat unmittelbar nach Registrierung funktioniert nicht

### ISSUE THREAD

**Issue by Letterus** [luki-ev/synod-android#18]
- Einen neuen Benutzer registrieren -> den Vorgang abschließen.
- Einen Direktchat beginnen (zB mit letterus)
- Problem: Ladeanzeige läuft unbegrenzt, auch wenn die Gegenseite den Chat annimmt. Neuer Raum wird nicht gejoint.
- Nach einem Neustart der App ist der Raum dann da, befindet sich aber bei "Räume", aber nicht bei "Direktnachrichten" (wo ich ihn erwarten würde).

Synod.im 0.21 - konnte das Problem mit RiotX 0.21 aus dem F-Droid-Store nicht reproduzieren.

**Comment by Letterus** [comment]
Ergänzung: In RiotX habe ich synod.im manuell eingegeben und nicht matrix.org verwendet. Für einen korrekten Vergleich müsste man vermutlich die Registrierung bei matrix.org testen.

**Comment by Letterus** [comment]
Fehler nicht regelmäßig reproduzierbar. Tritt etwa so auf:

```
im.vector.riotx.debug V/DefaultCrossSigningService$onUsersDeviceUpdate: ## CrossSigning - update trust for device ABC of user @user:matrix.org

…

2020-06-04 21:54:41.696 16986-16986/im.vector.riotx.debug E/TaskExecutor$execute: Task failed
    ServerError(error=MatrixError(code=M_UNKNOWN, message=Internal server error, consentUri=null, limitType=null, adminUri=null, retryAfterMillis=null, isSoftLogout=false, newLookupPepper=null), httpCode=500)
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:109)
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:77)
        at im.vector.matrix.android.internal.network.Request.execute(Request.kt:47)
        at im.vector.matrix.android.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
     Caused by: java.lang.RuntimeException: MatrixError(code=M_UNKNOWN, message=Internal server error, consentUri=null, limitType=null, adminUri=null, retryAfterMillis=null, isSoftLogout=false, newLookupPepper=null)
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:109) 
        at im.vector.matrix.android.internal.network.RetrofitExtensionsKt.toFailure(RetrofitExtensions.kt:77) 
        at im.vector.matrix.android.internal.network.Request.execute(Request.kt:47) 
        at im.vector.matrix.android.internal.network.Request$execute$1.invokeSuspend(Unknown Source:11) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740) 
```
